2. Разметка всех страниц проекта Глейси
htmlacademy-htmlcss/2145863-gllacy-35 pull request #2
Opened 2022-10-17 09:24 UTC by gitalexus

2022-10-17 17:42 UTC, Kartaviy-arteom requested changes

2022-10-17 17:42 UTC, Kartaviy-arteom commented on catalog.html
> +            <a class="navigation-controls-link" href="#"><span class="visually-hidden">Поиск</span></a>
это будет кнопка, по клику на которое показывается окно с поиском есть в стайлгайде

2022-10-17 17:42 UTC, Kartaviy-arteom commented on index.html
> +              <img class="promo-image" src="#" alt="Россыпь клубники.">
это будет декоративное изображение, по требованиям к проекту вставляется в css

2022-10-17 17:42 UTC, Kartaviy-arteom commented on index.html
> +            <a class="button popular-buy" href="#"><span class="visually-hidden">Купить мороженое</span></a>
это тоже кнопка, для добавления в корзину, тут не будет перехода на отдельную страницу

2022-10-17 17:42 UTC, Kartaviy-arteom commented on index.html
> +          <b class="contacts-text">+7 (812) 812-12-12</b>
это ссылка href="tel:

2022-10-17 17:42 UTC, Kartaviy-arteom commented on index.html
> +        <p class="copyright-text">Сделано в <a class="copiryght-link" href="#" target="_blank">.html academy</a> © 2021</p>
тут будет ссылка на htmlacademy

2022-10-17 17:42 UTC, Kartaviy-arteom commented on catalog.html
> +          <!-- фильтр по цене -->
сортировка внутри формы будет, в этом проекте фильтры  сортировка совмещены

2022-10-17 17:42 UTC, Kartaviy-arteom commented on catalog.html
> +            </a>
кнопка добавить в корзину

2022-10-18 08:43 UTC, gitalexus commented on catalog.html
> +            <a class="navigation-controls-link" href="#"><span class="visually-hidden">Поиск</span></a>
### Поменял во всех подобных случаях ссылки на кнопки
Но это же фундаментальный принцип **Html Academy**, вставлять везде ссылки вместо кнопок )
**Обоснование**: Поиск, Корзина, Окно авторизации, практически все должно загружаться в виде отдельной страницы, **_если вдруг не будет работать JS_**, который должент открывать модальные окошки.
Как я понимаю, на практике, так почти никто не делает. 
Но я нашел пример, когда это действительно сделано ссылками, а не кнопками на [apple.com](https://apple.com).

**Нажатие на кнопку поиска открывает отдельное модальное окно:**
![image](https://user-images.githubusercontent.com/87547180/196378810-217d92a1-de32-4f4c-a54d-a68f6e5e7d6b.png)

**Кнопка поиска реализована ввиде ссылки:**
![image](https://user-images.githubusercontent.com/87547180/196379077-1049341d-5431-4182-87ec-059a1a5848d4.png)

2022-10-18 10:19 UTC, Kartaviy-arteom commented on catalog.html
> +            <a class="navigation-controls-link" href="#"><span class="visually-hidden">Поиск</span></a>
я думал ты подправишь только поиск и оставишь ссылки на корзину и авторизацию.

2022-10-18 10:23 UTC, Kartaviy-arteom commented on catalog.html
> +            <a class="navigation-controls-link" href="#"><span class="visually-hidden">Поиск</span></a>
По этому вопросу есть два подхода: не пихать ссылки где должна быть кнопка и делать фолбеки, если обвалится js/
Я склоняюсь к тому, если у тебя есть альтернативная страница на которую можно перенаправить делать ссылку, если страницы отдельной нет, то ссылка не к чему. Т.е если далее не обрабатывать, то и не добавлять ее

2022-10-18 10:23 UTC, merged